/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/models/duck/rubber_duck_toy_4k.gltf -r src 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Duck(props) {
  const { nodes, materials } = useGLTF(
    "/assets/models/duck/rubber_duck_toy_4k.gltf"
  );
  return (
    <group {...props} dispose={null} scale={15}>
      <mesh
        geometry={nodes.rubber_duck_toy.geometry}
        material={materials.rubber_duck_toy}
      />
    </group>
  );
}

useGLTF.preload("/assets/models/duck/rubber_duck_toy_4k.gltf");
export default React.forwardRef(Duck);
